ARG NODE_VERSION=16-bullseye
FROM mcr.microsoft.com/devcontainers/javascript-node:0-${NODE_VERSION}

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>
